name: Latest blog post workflow
on: 
    schedule:
        - cron: '30 1 * * 2,6'
    workflow_dispatch:
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v4
            - uses: gautamkrishnar/blog-post-workflow@v1
              with: 
                max_post_count: "5"
                feed_list: "https://maheshrijal.com/rss.xml,https://maheshrijal.com/til/rss.xml"
